# Generated by Django 5.1.6 on 2025-02-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updataDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
